create table if not exists public.translation_sessions (
 id bigint generated by default as identity primary key,
 source_text text not null default '',
 translated_text text not null default '',
 target_language text not null default '',
 created_at timestamptz not null default now()
);
alter table public.translation_sessions enable row level security;
-- The write endpoint uses the server-only Supabase service-role key.
-- Do not expose SUPABASE_SERVICE_ROLE_KEY in browser code.